### ISSUE TITLE
My value.yaml

### ISSUE THREAD

**Issue by magikcypress** [magikcypress/helm-grav#1]
```
securityContext:
  enabled: true
  fsGroup: 33
  runAsUser: 33

persistence:
  ## grav data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  storageClass: "standard"
  dataDir:
    # Set this to false if you don't care to persist state between restarts.
    enabled: true
    Size: 10Gi


```
